flags: {}
packages:
- JEGL/
extra-deps:
- blaze-textual-0.2.1.0
- network-info-0.2.0.8
- persistent-postgresql-2.1.6
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.4.10.0
- uuid-1.3.11
- uuid-types-1.0.2
resolver: ghc-7.8
